### ISSUE TITLE
Identify suitable tests for RB3 Gen2 from github.com/Linaro/test-definitions

### ISSUE THREAD

**Issue by sbanerjee-quic** [quic-yocto/meta-qcom-hwe#22]
Need test cases to be identified for RB3 Gen2.
Tests case areas:

- BSP
- Multimedia
- Graphics
- Connectivity

**Comment by mwasilew** [comment]
This is what we currently run: 
```
    - from: git
      name: fs-resize
      path: automated/linux/fs-resize/fs-resize.yaml
      repository: http://github.com/linaro/test-definitions.git
    - from: git
      name: network-basic
      parameters:
        DHCLIENT: udhcpc -i
        INTERFACE: 'enP1p4s0u1u1'
        SKIP_INSTALL: true
      path: automated/linux/network-basic/network-basic.yaml
      repository: http://github.com/linaro/test-definitions.git
    - from: git
      name: docker
      parameters:
        IMAGE: public.ecr.aws/docker/library/hello-world
      path: automated/linux/docker/docker.yaml
      repository: http://github.com/linaro/test-definitions.git
    - from: git
      name: docker-networking
      parameters:
        IMAGE: public.ecr.aws/docker/library/alpine:latest
      path: automated/linux/docker-networking/docker-networking.yaml
      repository: http://github.com/linaro/test-definitions.git
    - from: git
      name: kernel-config-checker
      parameters:
        CONFIG_VALUES: CONFIG_CGROUPS
      path: automated/linux/kernel-config-checker/kernel-config-checker.yaml
      repository: http://github.com/linaro/test-definitions.git
    - from: git
      name: network-manager
      parameters:
        INTERFACE: 'enP1p4s0u1u1'
      path: automated/linux/network-manager/network-manager.yaml
      repository: http://github.com/linaro/test-definitions.git
    - from: git
      name: pkcs11
      parameters:
        PTOOL: pkcs11-tool --module /usr/lib/libckteec.so.0.1.0
        USE_SE05X: 'false'
      path: automated/linux/pkcs11/pkcs11.yaml
      repository: http://github.com/linaro/test-definitions.git 
     - from: git
      name: wlan-smoke
      parameters:
        DEVICE: 'wlan0'
      path: automated/linux/wlan-smoke/wlan-smoke.yaml
      repository: http://github.com/linaro/test-definitions.git
    - from: git
      name: wlan-download
      parameters:
        DEVICE: 'wlan0'
        ETHERNET_DEVICE: 'enP1p4s0u1u1'
        FILE_CHECKSUM: 8388f7232b400bdc80279668847f90da
        FILE_URL: http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso
        TIME_DELAY: 120s
      path: automated/linux/wlan-download/wlan-download.yaml
      repository: http://github.com/linaro/test-definitions.git 
```

pkcs11 obviously fails as it defaults to op-tee implementation. There are probably a few more tests that would exercise BSP, but someone more experienced with kernel could help selecting these.
